---
### common

- name: "install git"
  apt:
    name: git
    state: latest
  when: ansible_pkg_mgr == 'apt'


- name: "apt install make"
  apt:
    name: make


- name: "install unzip"
  apt:
    name: unzip
    state: latest
  when: ansible_pkg_mgr == 'apt'


- name: Install ufw
  apt:
    name: ufw
    update_cache: true

- name : Turn on Firewall
  ufw:
    state: enabled
    policy: allow

- name : Allowing SSH port
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name : Allowing port http (port 80)
  ufw :
    rule: allow
    port: '80'
    proto: tcp

- name : Allowing port http (port 22)
  ufw :
    rule: allow
    port: '22'
    proto: tcp

- name : Allowing port http (port 8000)
  ufw :
    rule: allow
    port: '8000'
    proto: tcp

- command: "{{ item }}"
  with_items:
    - sudo ufw allow 8000

- name: Create Folder /app if not exist
  file:
    path: /app
    mode: 0755
    state: directory

- name: copy files and directories /to server
  copy: 
    src: "{{ item }}"
    dest: /app
  loop:
    - ./myproject.zip
  register: copy_output
- debug: var=copy_output

- command: "{{ item }}"
  with_items:
    - unzip /app/myproject.zip -d /app 
    - pip3 install django==2.2.20
    - python /app/myproject/manage.py runserver
